In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn import datasets

iris = datasets.load_iris()

In [ ]:
data1 = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])
data1

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0.0
1,4.9,3.0,1.4,0.2,0.0
2,4.7,3.2,1.3,0.2,0.0
3,4.6,3.1,1.5,0.2,0.0
4,5.0,3.6,1.4,0.2,0.0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2.0
146,6.3,2.5,5.0,1.9,2.0
147,6.5,3.0,5.2,2.0,2.0
148,6.2,3.4,5.4,2.3,2.0
149,5.9,3.0,5.1,1.8,2.0

# Ejercicio 1: 

Demuestra que la matriz de correlaciÃ³n es una matriz simÃ©trica por los siguientes mÃ©todos

*Usando Trnaspuesta

*Usando las matrices triangulares

In [ ]:
# usando transpuesta
data_cor = data1.corr()
data_cor_t = data_cor.T
#comparar
data_cor == data_cor_t

# funcion de numpy
np.array_equal(data_cor, data_cor_t)

In [ ]:
data_cor

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
sepal length (cm),1.000000,-0.117570,0.871754,0.817941,0.782561
sepal width (cm),-0.117570,1.000000,-0.428440,-0.366126,-0.426658
petal length (cm),0.871754,-0.428440,1.000000,0.962865,0.949035
petal width (cm),0.817941,-0.366126,0.962865,1.000000,0.956547
target,0.782561,-0.426658,0.949035,0.956547,1.000000

In [ ]:
#2 
tri_sup = np.triu(data_cor, 0 )
tri_inf = np.tril(data_cor, -1)
#primer intento
tri_inf + tri_sup == data_cor
# segundo intento
np.array_equal(data_cor, tri_inf + tri_sup )

False

In [ ]:
# tercera forma
tri_sup = np.triu(data_cor, 0 )
tri_inf = np.tril(data_cor, 0)
tri_sup == tri_inf.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Ejercicio 2
Obten la matriz inversa de la matriz de correlaciÃ³n

In [ ]:
data_cor_inv = np.linalg.inv(data_cor)

# metodo : adjunta / determinante 
np.linalg.det(data_cor)

0.0005644782038051219

# Ejercicio 3
Â¿QuÃ© operaciÃ³n(es) harÃ­as para obtener la matriz identidad?

In [ ]:
round(data_cor.dot(data_cor_inv))
data_cor

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
sepal length (cm),1.000000,-0.117570,0.871754,0.817941,0.782561
sepal width (cm),-0.117570,1.000000,-0.428440,-0.366126,-0.426658
petal length (cm),0.871754,-0.428440,1.000000,0.962865,0.949035
petal width (cm),0.817941,-0.366126,0.962865,1.000000,0.956547
target,0.782561,-0.426658,0.949035,0.956547,1.000000

In [ ]:
np.eye(data_cor.shape[0])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
data_cor.dot(np.eye(data_cor.shape[0]))

                          0         1         2         3         4
sepal length (cm)  1.000000 -0.117570  0.871754  0.817941  0.782561
sepal width (cm)  -0.117570  1.000000 -0.428440 -0.366126 -0.426658
petal length (cm)  0.871754 -0.428440  1.000000  0.962865  0.949035
petal width (cm)   0.817941 -0.366126  0.962865  1.000000  0.956547
target             0.782561 -0.426658  0.949035  0.956547  1.000000